server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mappers/*Dao.xml

spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: custom,news2020,news2021,news2022,news2023,news2024
      custom:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.0.113:3306/custom?characterEncoding=utf-8
        username: root
        password: 016312Aj.713
      news2020:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.0.113:3306/t_news_2020?characterEncoding=utf-8
        username: root
        password: 016312Aj.713
      news2021:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.0.113:3306/t_news_2021?characterEncoding=utf-8
        username: root
        password: 016312Aj.713
      news2022:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.0.113:3306/t_news_2022?characterEncoding=utf-8
        username: root
        password: 016312Aj.713
      news2023:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.0.113:3306/t_news_2023?characterEncoding=utf-8
        username: root
        password: 016312Aj.713
      news2024:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.0.113:3306/t_news_2024?characterEncoding=utf-8
        username: root
        password: 016312Aj.713
    sharding:
      default-database-strategy:
        standard:
          precise-algorithm-class-name: com.aj.shardingjdbc.news.config.PreciseModuloDatabaseShardingAlgorithm
          sharding-column: create_time
      tables:
        newsvisit:
          actual-data-nodes: news$->{2020..2024}.t_news_visit_0$->{1..9},news$->{2020..2024}.t_news_visit_1$->{0..2}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            standard:
              precise-algorithm-class-name: com.aj.shardingjdbc.news.config.PreciseModuloTableShardingAlgorithm
              sharding-column: create_time
        news:
          actual-data-nodes: custom.t_news_0${0..9}
          key-generator:
            column: id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_news_0${id.longValue() % 10}
      default-data-source-name: custom #库分片策略为none时一定要设置默认数据源，否则应用无法启动
