server:
  port: 8762

eureka:
  client:
     #不注册自己,自己本身就是注册中心服务
    registerWithEureka: false
     #不抓取服务,自己本身就是注册中心服务
    fetchRegistry: false

#eureka:
#  instance:
#    hostname: peer2
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/